-- Cape & Cart H1 Growth Campaign Snowflake setup
-- Run this in Snowsight as ACCOUNTADMIN, then load each CSV listed in snowflake_load_manifest.csv.
CREATE WAREHOUSE IF NOT EXISTS CAPE_CART_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS CAPE_CART_H1_GROWTH;
USE WAREHOUSE CAPE_CART_WH;
USE DATABASE CAPE_CART_H1_GROWTH;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS ML;
CREATE OR REPLACE FILE FORMAT CSV_HEADER_FORMAT TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' ESCAPE_UNENCLOSED_FIELD = NONE EMPTY_FIELD_AS_NULL = TRUE NULL_IF = ('', 'NULL', 'null');

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\bronze\ga4_events_raw.csv
CREATE OR REPLACE TABLE RAW.GA4_EVENTS_RAW (
  "EVENT_DATE" VARCHAR,
  "EVENT_TIMESTAMP" VARCHAR,
  "EVENT_NAME" VARCHAR,
  "USER_PSEUDO_ID" VARCHAR,
  "SESSION_ID" VARCHAR,
  "GEO_COUNTRY" VARCHAR,
  "GEO_CITY" VARCHAR,
  "DEVICE_CATEGORY" VARCHAR,
  "TRAFFIC_SOURCE_MEDIUM" VARCHAR,
  "TRAFFIC_SOURCE_SOURCE" VARCHAR,
  "TRAFFIC_SOURCE_NAME" VARCHAR,
  "PAGE_LOCATION" VARCHAR,
  "EVENT_VALUE_IN_USD" VARCHAR,
  "GA_SESSION_NUMBER" VARCHAR,
  "IS_ACTIVE_USER" VARCHAR,
  "PLATFORM" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\bronze\google_ads_raw.csv
CREATE OR REPLACE TABLE RAW.GOOGLE_ADS_RAW (
  "DATE" VARCHAR,
  "CUSTOMER_ID" VARCHAR,
  "CAMPAIGN_ID" VARCHAR,
  "CAMPAIGN_NAME" VARCHAR,
  "CAMPAIGN_STATUS" VARCHAR,
  "AD_GROUP_ID" VARCHAR,
  "IMPRESSIONS" VARCHAR,
  "CLICKS" VARCHAR,
  "COST_MICROS" VARCHAR,
  "CONVERSIONS" VARCHAR,
  "CONVERSION_VALUE" VARCHAR,
  "CURRENCY_CODE" VARCHAR,
  "DEVICE" VARCHAR,
  "NETWORK" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\bronze\youtube_raw.csv
CREATE OR REPLACE TABLE RAW.YOUTUBE_RAW (
  "DATE" VARCHAR,
  "CHANNEL_ID" VARCHAR,
  "VIDEO_ID" VARCHAR,
  "VIDEO_TITLE" VARCHAR,
  "COUNTRY" VARCHAR,
  "DEVICE_TYPE" VARCHAR,
  "TRAFFIC_SOURCE_TYPE" VARCHAR,
  "VIEWS" VARCHAR,
  "WATCH_TIME_MINUTES" VARCHAR,
  "IMPRESSIONS" VARCHAR,
  "IMPRESSIONS_CLICK_THROUGH_RATE" VARCHAR,
  "LIKES" VARCHAR,
  "COMMENTS" VARCHAR,
  "ESTIMATED_REVENUE_USD" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\bronze\transactional_raw\products_raw.csv
CREATE OR REPLACE TABLE RAW.ECOM_PRODUCTS_RAW (
  "PRODUCT_ID" VARCHAR,
  "SKU" VARCHAR,
  "PRODUCT_NAME" VARCHAR,
  "CATEGORY" VARCHAR,
  "BASE_PRICE_ZAR" VARCHAR,
  "GROSS_MARGIN_PCT" VARCHAR,
  "LEAD_CAMPAIGN_CHANNEL" VARCHAR,
  "CAMPAIGN_FOCUS_FLAG" VARCHAR,
  "PERFORMANCE_GROUP" VARCHAR,
  "SOURCE_NOTE" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\bronze\transactional_raw\customers_raw.csv
CREATE OR REPLACE TABLE RAW.ECOM_CUSTOMERS_RAW (
  "CUSTOMER_ID" VARCHAR,
  "FIRST_SEEN_DATE" VARCHAR,
  "PROVINCE" VARCHAR,
  "CITY" VARCHAR,
  "CUSTOMER_SEGMENT" VARCHAR,
  "CONSENT_STATUS" VARCHAR,
  "SOURCE_NOTE" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\bronze\transactional_raw\orders_raw.csv
CREATE OR REPLACE TABLE RAW.ECOM_ORDERS_RAW (
  "ORDER_ID" VARCHAR,
  "ORDER_DATE" VARCHAR,
  "CUSTOMER_ID" VARCHAR,
  "ATTRIBUTION_CHANNEL" VARCHAR,
  "CAMPAIGN_NAME" VARCHAR,
  "IS_PAID_ATTRIBUTED" VARCHAR,
  "ORDER_SUBTOTAL_ZAR" VARCHAR,
  "DISCOUNT_TOTAL_ZAR" VARCHAR,
  "SHIPPING_FEE_ZAR" VARCHAR,
  "ORDER_TOTAL_ZAR" VARCHAR,
  "PAYMENT_METHOD" VARCHAR,
  "ORDER_STATUS" VARCHAR,
  "SOURCE_NOTE" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\bronze\transactional_raw\order_items_raw.csv
CREATE OR REPLACE TABLE RAW.ECOM_ORDER_ITEMS_RAW (
  "ORDER_ITEM_ID" VARCHAR,
  "ORDER_ID" VARCHAR,
  "PRODUCT_ID" VARCHAR,
  "SKU" VARCHAR,
  "PRODUCT_NAME" VARCHAR,
  "CATEGORY" VARCHAR,
  "QUANTITY" VARCHAR,
  "UNIT_PRICE_ZAR" VARCHAR,
  "DISCOUNT_ZAR" VARCHAR,
  "LINE_REVENUE_ZAR" VARCHAR,
  "GROSS_MARGIN_PCT" VARCHAR,
  "SOURCE_NOTE" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\bronze\transactional_raw\campaign_touchpoints_raw.csv
CREATE OR REPLACE TABLE RAW.ECOM_CAMPAIGN_TOUCHPOINTS_RAW (
  "TOUCHPOINT_ID" VARCHAR,
  "ORDER_ID" VARCHAR,
  "CUSTOMER_ID" VARCHAR,
  "TOUCHPOINT_DATE" VARCHAR,
  "CHANNEL" VARCHAR,
  "CAMPAIGN_NAME" VARCHAR,
  "ATTRIBUTION_MODEL" VARCHAR,
  "ATTRIBUTED_CONVERSION" VARCHAR,
  "VIEW_THROUGH_FLAG" VARCHAR,
  "SOURCE_NOTE" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\silver\transactional\products_clean.csv
CREATE OR REPLACE TABLE SILVER.PRODUCTS_CLEAN (
  "PRODUCT_ID" VARCHAR,
  "SKU" VARCHAR,
  "PRODUCT_NAME" VARCHAR,
  "CATEGORY" VARCHAR,
  "BASE_PRICE_ZAR" VARCHAR,
  "GROSS_MARGIN_PCT" VARCHAR,
  "LEAD_CAMPAIGN_CHANNEL" VARCHAR,
  "CAMPAIGN_FOCUS_FLAG" VARCHAR,
  "PERFORMANCE_GROUP" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\silver\transactional\customers_clean.csv
CREATE OR REPLACE TABLE SILVER.CUSTOMERS_CLEAN (
  "CUSTOMER_ID" VARCHAR,
  "FIRST_SEEN_DATE" VARCHAR,
  "PROVINCE" VARCHAR,
  "CITY" VARCHAR,
  "CUSTOMER_SEGMENT" VARCHAR,
  "CONSENT_STATUS" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\silver\transactional\orders_clean.csv
CREATE OR REPLACE TABLE SILVER.ORDERS_CLEAN (
  "ORDER_ID" VARCHAR,
  "ORDER_DATE" VARCHAR,
  "CUSTOMER_ID" VARCHAR,
  "ATTRIBUTION_CHANNEL" VARCHAR,
  "CAMPAIGN_NAME" VARCHAR,
  "IS_PAID_ATTRIBUTED" VARCHAR,
  "ORDER_SUBTOTAL_ZAR" VARCHAR,
  "DISCOUNT_TOTAL_ZAR" VARCHAR,
  "SHIPPING_FEE_ZAR" VARCHAR,
  "ORDER_TOTAL_ZAR" VARCHAR,
  "PAYMENT_METHOD" VARCHAR,
  "ORDER_STATUS" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\silver\transactional\order_items_clean.csv
CREATE OR REPLACE TABLE SILVER.ORDER_ITEMS_CLEAN (
  "ORDER_ITEM_ID" VARCHAR,
  "ORDER_ID" VARCHAR,
  "PRODUCT_ID" VARCHAR,
  "SKU" VARCHAR,
  "PRODUCT_NAME" VARCHAR,
  "CATEGORY" VARCHAR,
  "QUANTITY" VARCHAR,
  "UNIT_PRICE_ZAR" VARCHAR,
  "DISCOUNT_ZAR" VARCHAR,
  "LINE_REVENUE_ZAR" VARCHAR,
  "GROSS_MARGIN_PCT" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\silver\transactional\campaign_touchpoints_clean.csv
CREATE OR REPLACE TABLE SILVER.CAMPAIGN_TOUCHPOINTS_CLEAN (
  "TOUCHPOINT_ID" VARCHAR,
  "ORDER_ID" VARCHAR,
  "CUSTOMER_ID" VARCHAR,
  "TOUCHPOINT_DATE" VARCHAR,
  "CHANNEL" VARCHAR,
  "CAMPAIGN_NAME" VARCHAR,
  "ATTRIBUTION_MODEL" VARCHAR,
  "ATTRIBUTED_CONVERSION" VARCHAR,
  "VIEW_THROUGH_FLAG" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\silver\transactional\transactional_quarantine.csv
CREATE OR REPLACE TABLE SILVER.TRANSACTIONAL_QUARANTINE (
  "SOURCE_TABLE" VARCHAR,
  "GRAIN_ID" VARCHAR,
  "REJECT_REASON" VARCHAR,
  "RAW_PAYLOAD" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\silver\transactional\transactional_data_quality_summary.csv
CREATE OR REPLACE TABLE SILVER.TRANSACTIONAL_DATA_QUALITY_SUMMARY (
  "METRIC" VARCHAR,
  "VALUE" VARCHAR,
  "NOTE" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\gold\gold_product_performance.csv
CREATE OR REPLACE TABLE GOLD.GOLD_PRODUCT_PERFORMANCE (
  "PRODUCT_ID" VARCHAR,
  "PRODUCT_NAME" VARCHAR,
  "CATEGORY" VARCHAR,
  "UNITS_SOLD" VARCHAR,
  "NET_REVENUE_ZAR" VARCHAR,
  "GROSS_MARGIN_PCT" VARCHAR,
  "LEAD_CAMPAIGN_CHANNEL" VARCHAR,
  "CAMPAIGN_FOCUS_FLAG" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\transactional\products.csv
CREATE OR REPLACE TABLE ANALYTICS.PRODUCTS (
  "PRODUCT_ID" VARCHAR,
  "SKU" VARCHAR,
  "PRODUCT_NAME" VARCHAR,
  "CATEGORY" VARCHAR,
  "BASE_PRICE_ZAR" VARCHAR,
  "GROSS_MARGIN_PCT" VARCHAR,
  "LEAD_CAMPAIGN_CHANNEL" VARCHAR,
  "CAMPAIGN_FOCUS_FLAG" VARCHAR,
  "PERFORMANCE_GROUP" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\transactional\customers.csv
CREATE OR REPLACE TABLE ANALYTICS.CUSTOMERS (
  "CUSTOMER_ID" VARCHAR,
  "FIRST_SEEN_DATE" VARCHAR,
  "PROVINCE" VARCHAR,
  "CITY" VARCHAR,
  "CUSTOMER_SEGMENT" VARCHAR,
  "CONSENT_STATUS" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\transactional\orders.csv
CREATE OR REPLACE TABLE ANALYTICS.ORDERS (
  "ORDER_ID" VARCHAR,
  "ORDER_DATE" VARCHAR,
  "CUSTOMER_ID" VARCHAR,
  "ATTRIBUTION_CHANNEL" VARCHAR,
  "CAMPAIGN_NAME" VARCHAR,
  "IS_PAID_ATTRIBUTED" VARCHAR,
  "ORDER_SUBTOTAL_ZAR" VARCHAR,
  "DISCOUNT_TOTAL_ZAR" VARCHAR,
  "SHIPPING_FEE_ZAR" VARCHAR,
  "ORDER_TOTAL_ZAR" VARCHAR,
  "PAYMENT_METHOD" VARCHAR,
  "ORDER_STATUS" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\transactional\order_items.csv
CREATE OR REPLACE TABLE ANALYTICS.ORDER_ITEMS (
  "ORDER_ITEM_ID" VARCHAR,
  "ORDER_ID" VARCHAR,
  "PRODUCT_ID" VARCHAR,
  "SKU" VARCHAR,
  "PRODUCT_NAME" VARCHAR,
  "CATEGORY" VARCHAR,
  "QUANTITY" VARCHAR,
  "UNIT_PRICE_ZAR" VARCHAR,
  "DISCOUNT_ZAR" VARCHAR,
  "LINE_REVENUE_ZAR" VARCHAR,
  "GROSS_MARGIN_PCT" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\transactional\campaign_touchpoints.csv
CREATE OR REPLACE TABLE ANALYTICS.CAMPAIGN_TOUCHPOINTS (
  "TOUCHPOINT_ID" VARCHAR,
  "ORDER_ID" VARCHAR,
  "CUSTOMER_ID" VARCHAR,
  "TOUCHPOINT_DATE" VARCHAR,
  "CHANNEL" VARCHAR,
  "CAMPAIGN_NAME" VARCHAR,
  "ATTRIBUTION_MODEL" VARCHAR,
  "ATTRIBUTED_CONVERSION" VARCHAR,
  "VIEW_THROUGH_FLAG" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\transactional\product_campaign_attribution_summary.csv
CREATE OR REPLACE TABLE ANALYTICS.PRODUCT_CAMPAIGN_ATTRIBUTION_SUMMARY (
  "RANK_GROUP" VARCHAR,
  "RANK" VARCHAR,
  "PRODUCT_ID" VARCHAR,
  "PRODUCT_NAME" VARCHAR,
  "CATEGORY" VARCHAR,
  "LEAD_CHANNEL" VARCHAR,
  "ATTRIBUTED_SPEND_ZAR" VARCHAR,
  "ATTRIBUTED_REVENUE_ZAR" VARCHAR,
  "ROAS" VARCHAR,
  "ATTRIBUTED_CONVERSIONS" VARCHAR,
  "RECOMMENDED_ACTION" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\transactional\TRANSACTIONAL_DATA_MANIFEST.csv
CREATE OR REPLACE TABLE ANALYTICS.TRANSACTIONAL_DATA_MANIFEST (
  "LAYER" VARCHAR,
  "FILE_NAME" VARCHAR,
  "GRAIN" VARCHAR,
  "PURPOSE" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\ml\ml_model_registry.csv
CREATE OR REPLACE TABLE ML.ML_MODEL_REGISTRY (
  "MODEL_ID" VARCHAR,
  "BUSINESS_USE" VARCHAR,
  "TRAINING_TABLE" VARCHAR,
  "TARGET" VARCHAR,
  "ALGORITHM" VARCHAR,
  "PRIMARY_KPI" VARCHAR,
  "PRIMARY_KPI_VALUE" VARCHAR,
  "SECONDARY_KPIS" VARCHAR,
  "ACTIVATION_KPI" VARCHAR,
  "RECOMMENDED_USE" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\ml\customer_ml_scores.csv
CREATE OR REPLACE TABLE ML.CUSTOMER_ML_SCORES (
  "CUSTOMER_ID" VARCHAR,
  "PROVINCE" VARCHAR,
  "CUSTOMER_SEGMENT" VARCHAR,
  "CONSENT_STATUS" VARCHAR,
  "ORDERS_H1" VARCHAR,
  "REVENUE_H1_ZAR" VARCHAR,
  "DISTINCT_CATEGORIES" VARCHAR,
  "RECENCY_DAYS" VARCHAR,
  "PURCHASE_PROPENSITY_SCORE" VARCHAR,
  "PURCHASE_PROPENSITY_BAND" VARCHAR,
  "CHURN_RISK_SCORE" VARCHAR,
  "RECOMMENDED_AUDIENCE" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\ml\next_best_product_recommendations.csv
CREATE OR REPLACE TABLE ML.NEXT_BEST_PRODUCT_RECOMMENDATIONS (
  "CUSTOMER_ID" VARCHAR,
  "SOURCE_CATEGORY" VARCHAR,
  "RECOMMENDED_PRODUCT_ID" VARCHAR,
  "RECOMMENDED_PRODUCT_NAME" VARCHAR,
  "RECOMMENDED_CATEGORY" VARCHAR,
  "RECOMMENDATION_SCORE" VARCHAR,
  "EXPECTED_ORDER_VALUE_ZAR" VARCHAR,
  "ACTIVATION_CHANNEL" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\ml\channel_roas_forecast.csv
CREATE OR REPLACE TABLE ML.CHANNEL_ROAS_FORECAST (
  "CHANNEL" VARCHAR,
  "MONTH" VARCHAR,
  "ACTUAL_ROAS" VARCHAR,
  "FORECAST_ROAS" VARCHAR,
  "LOWER_BOUND" VARCHAR,
  "UPPER_BOUND" VARCHAR,
  "MODEL_ID" VARCHAR
);

-- Source file: C:\Users\Anthony.DESKTOP-ES5HL78\Downloads\GCP-Marketing-Analytics-Platform\data\ml\ML_DATA_MANIFEST.csv
CREATE OR REPLACE TABLE ML.ML_DATA_MANIFEST (
  "FILE_NAME" VARCHAR,
  "GRAIN" VARCHAR,
  "PURPOSE" VARCHAR
);


CREATE OR REPLACE VIEW ANALYTICS.VW_CAMPAIGN_EXECUTIVE_SCORECARD AS
SELECT
  'Cape & Cart H1 Growth Campaign' AS CASE_STUDY,
  (SELECT COUNT(*) FROM RAW.GA4_EVENTS_RAW) AS GA4_EVENTS,
  (SELECT COUNT(*) FROM RAW.GOOGLE_ADS_RAW) AS GOOGLE_ADS_ROWS,
  (SELECT COUNT(*) FROM RAW.YOUTUBE_RAW) AS YOUTUBE_ROWS,
  (SELECT COUNT(*) FROM RAW.ECOM_ORDERS_RAW) AS RAW_ECOM_ORDERS,
  (SELECT COUNT(*) FROM SILVER.TRANSACTIONAL_QUARANTINE) AS ECOM_QUARANTINED_ROWS,
  (SELECT COUNT(*) FROM ANALYTICS.ORDERS) AS ORDERS_H1,
  (SELECT ROUND(SUM(TRY_TO_DECIMAL(ORDER_TOTAL_ZAR, 18, 2)), 2) FROM ANALYTICS.ORDERS) AS REVENUE_ZAR,
  (SELECT COUNT(*) FROM ANALYTICS.CUSTOMERS) AS CUSTOMERS,
  (SELECT COUNT(*) FROM ANALYTICS.PRODUCTS) AS PRODUCTS;

CREATE OR REPLACE VIEW ANALYTICS.VW_CHANNEL_PERFORMANCE AS
SELECT
  ATTRIBUTION_CHANNEL,
  COUNT(*) AS ORDERS,
  ROUND(SUM(TRY_TO_DECIMAL(ORDER_TOTAL_ZAR, 18, 2)), 2) AS REVENUE_ZAR,
  ROUND(AVG(TRY_TO_DECIMAL(ORDER_TOTAL_ZAR, 18, 2)), 2) AS AOV_ZAR,
  SUM(IFF(LOWER(IS_PAID_ATTRIBUTED) = 'true', 1, 0)) AS PAID_ATTRIBUTED_ORDERS
FROM ANALYTICS.ORDERS
GROUP BY ATTRIBUTION_CHANNEL;

CREATE OR REPLACE VIEW ANALYTICS.VW_TRANSACTIONAL_DQ AS
SELECT
  SOURCE_TABLE,
  REJECT_REASON,
  COUNT(*) AS REJECTED_ROWS
FROM SILVER.TRANSACTIONAL_QUARANTINE
GROUP BY SOURCE_TABLE, REJECT_REASON;

CREATE OR REPLACE VIEW ANALYTICS.VW_TOP_10_PRODUCTS AS
SELECT *
FROM ANALYTICS.PRODUCT_CAMPAIGN_ATTRIBUTION_SUMMARY
WHERE RANK_GROUP = 'top_10'
ORDER BY TRY_TO_NUMBER(RANK);

CREATE OR REPLACE VIEW ANALYTICS.VW_WORST_10_PRODUCTS AS
SELECT *
FROM ANALYTICS.PRODUCT_CAMPAIGN_ATTRIBUTION_SUMMARY
WHERE RANK_GROUP = 'worst_10'
ORDER BY TRY_TO_NUMBER(RANK);

CREATE OR REPLACE TABLE ML.CUSTOMER_FEATURES_SNOWFLAKE AS
SELECT
  c.CUSTOMER_ID,
  c.PROVINCE,
  c.CITY,
  c.CUSTOMER_SEGMENT,
  c.CONSENT_STATUS,
  COUNT(o.ORDER_ID) AS ORDERS_H1,
  COALESCE(SUM(TRY_TO_DECIMAL(o.ORDER_TOTAL_ZAR, 18, 2)), 0) AS REVENUE_H1_ZAR,
  COUNT(DISTINCT oi.CATEGORY) AS DISTINCT_CATEGORIES,
  DATEDIFF('day', MAX(TRY_TO_DATE(o.ORDER_DATE)), TO_DATE('2024-06-30')) AS RECENCY_DAYS,
  COALESCE(SUM(IFF(LOWER(o.IS_PAID_ATTRIBUTED) = 'true', 1, 0)), 0) AS PAID_ATTRIBUTED_ORDERS
FROM ANALYTICS.CUSTOMERS c
LEFT JOIN ANALYTICS.ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
LEFT JOIN ANALYTICS.ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
GROUP BY c.CUSTOMER_ID, c.PROVINCE, c.CITY, c.CUSTOMER_SEGMENT, c.CONSENT_STATUS;

CREATE OR REPLACE TABLE ML.CUSTOMER_ML_SCORES_SNOWFLAKE AS
SELECT
  *,
  ROUND(1 / (1 + EXP(-(
    -2.20
    + 0.34 * LEAST(ORDERS_H1, 8)
    + 0.00018 * LEAST(REVENUE_H1_ZAR, 25000)
    + 0.28 * LEAST(DISTINCT_CATEGORIES, 6)
    - 0.018 * LEAST(COALESCE(RECENCY_DAYS, 180), 180)
    + 0.20 * IFF(CONSENT_STATUS = 'granted', 1, 0)
  ))), 4) AS PURCHASE_PROPENSITY_SCORE,
  ROUND(1 / (1 + EXP(-(
    -1.45
    + 0.030 * LEAST(COALESCE(RECENCY_DAYS, 180), 180)
    - 0.26 * LEAST(ORDERS_H1, 8)
    - 0.00010 * LEAST(REVENUE_H1_ZAR, 25000)
    + 0.18 * IFF(CONSENT_STATUS <> 'granted', 1, 0)
  ))), 4) AS CHURN_RISK_SCORE
FROM ML.CUSTOMER_FEATURES_SNOWFLAKE;

CREATE OR REPLACE VIEW ML.VW_HIGH_PROPENSITY_AUDIENCE AS
SELECT CUSTOMER_ID, PROVINCE, CUSTOMER_SEGMENT, ORDERS_H1, REVENUE_H1_ZAR, PURCHASE_PROPENSITY_SCORE
FROM ML.CUSTOMER_ML_SCORES_SNOWFLAKE
WHERE PURCHASE_PROPENSITY_SCORE >= 0.45
ORDER BY PURCHASE_PROPENSITY_SCORE DESC;

CREATE OR REPLACE VIEW ML.VW_CHURN_REACTIVATION_AUDIENCE AS
SELECT CUSTOMER_ID, PROVINCE, CUSTOMER_SEGMENT, RECENCY_DAYS, CHURN_RISK_SCORE
FROM ML.CUSTOMER_ML_SCORES_SNOWFLAKE
WHERE CHURN_RISK_SCORE >= 0.58
ORDER BY CHURN_RISK_SCORE DESC;

CREATE OR REPLACE VIEW ML.VW_ROAS_FORECAST_ACTIONS AS
SELECT
  CHANNEL,
  MONTH,
  TRY_TO_DECIMAL(ACTUAL_ROAS, 8, 2) AS ACTUAL_ROAS,
  TRY_TO_DECIMAL(FORECAST_ROAS, 8, 2) AS FORECAST_ROAS,
  CASE
    WHEN TRY_TO_DECIMAL(FORECAST_ROAS, 8, 2) >= 4.0 THEN 'Scale budget'
    WHEN TRY_TO_DECIMAL(FORECAST_ROAS, 8, 2) >= 3.0 THEN 'Hold and test creative'
    ELSE 'Reduce waste and rebuild audience'
  END AS RECOMMENDED_ACTION
FROM ML.CHANNEL_ROAS_FORECAST;

CREATE OR REPLACE VIEW ML.ML_KPI_SCORECARD AS
SELECT
  (SELECT COUNT(*) FROM ML.CUSTOMER_ML_SCORES_SNOWFLAKE) AS SCORED_CUSTOMERS,
  (SELECT COUNT(*) FROM ML.VW_HIGH_PROPENSITY_AUDIENCE) AS HIGH_OR_WARM_PROPENSITY_CUSTOMERS,
  (SELECT COUNT(*) FROM ML.VW_CHURN_REACTIVATION_AUDIENCE) AS CHURN_REACTIVATION_CUSTOMERS,
  (SELECT COUNT(*) FROM ML.VW_ROAS_FORECAST_ACTIONS WHERE RECOMMENDED_ACTION = 'Scale budget') AS SCALE_BUDGET_CHANNEL_MONTHS;
